---

- hosts: demo
  become: yes
  connection: ssh
  remote_user: ansible
  vars:
          - new_password: 'abcd1234'
  tasks:
          - name: Add a new user with name newUser
            user:
                    name=newUser
                    password={{ new_password }}

          - name: Add newUser to sudoers
            copy:
                    dest: "/etc/sudoers.d/newUser"
                    content: "newUser ALL=(ALL) NOPASSWD: ALL"

          - name: Deploy SSH key
            authorized_key: user=newUser
                    key={{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}
                    state=present

          - name: Disable password authentication
            lineinfile:
                    dest=/etc/ssh/sshd_config
                    regexp='^PasswordAuthentication'
                    line="PasswordAuthentication no"
                    state=present
                    backup=yes
            notify:
                    - restart ssh

          - name: Disable root login
            lineinfile:
                   dest=/etc/ssh/sshd_config
                   regexp='^PermitRootLogin'
                   line="PermitRootLogin no"
                   state=present
                   backup=yes
            notify:
                    - restart ssh

          - name: Update APT package cache
            yum:
                    name: '*'
                    state: latest

          - name: Install required packages
            yum: install '{{ item }}' -y
            with_items: ubuntu_common_required_packages

          - name: Setup ufw
            ufw: state=enabled policy=deny
            when: ansible_os_family == 'Debian'

  handlers:
          - name: restart ssh
            ansible.builtin.service:
                    name=sshd
                    state=restarted

